### ISSUE TITLE
display of list of entries in other tables referencing the table i am editing is not configurable

### ISSUE THREAD

**Issue by beerockxs** [bstroebl/DataDrivenInputMask#20]
As far as I can tell, I can't configure the display of the tables (e.g. with aliases) that show other tables that have a foreign key referencing the table I am currently editing. Am I just missing something, or is this currently not possible?

**Comment by bstroebl** [comment]
Not out of the box. You have to code what you need using Python (in a plugin), e.g. for a combobox:
`ddManager = ddmanager.DdManager(self.iface)`
 `aWidget = ddManager.getInputWidget(layer,"Fieldname") # find the DdWidget`
 `if aWidget != None:`
 `    anAttribute = aWidget.attribute # get the widget's DdAttribute`
 `    oldQuery = anAttribute.getQueryForCbx() # get the query`
 `    newQuery = oldQuery.replace(";", " WHERE id IN (50,51,52,53);") # manipulate the query`
 `    anAttribute.setQueryForCbx(newQuery) # replace the original query with the manipulated one`
This shows only the values with id 50,51,52 and 53 in the combobox.

For n2m relations dduserclass.DdN2mCheckableTableWidget is a good starting point, as it offers the use of catalogues - only features in the chosen catalogue are available.

**Comment by bstroebl** [comment]
Ok, I see, you have to configure it in the configuration dialogue, opened with `configure mask.` 
The `field_name` is the name of the referenced table, enter any `field_alias` you like.
But I doubt this works if you have multiple FK relations, because the same `field_name` appears several times and the configuration only uses the `field_name` to identify a field so I expect the `field_alias` to be purely random then.

Why would you have multiple foreign key relations with one table? This seems a strange database design to me. Could you attach your DDL so I can understand your problem?

**Comment by beerockxs** [comment]
My database is for a road database, and for each section of the road, I store the source network node and the destination network node, therefor I have two foreign keys referencing the network node table.

**Comment by beerockxs** [comment]
Exactly. Your suggestion would work just fine.

**Comment by beerockxs** [comment]
Is it possible to define aliases for the field names displayed as column headers in the tables displayed for each foreign key relation?

**Comment by bstroebl** [comment]
Configure the mask for table in question (e.g. roads) and define aliases there.
