### ISSUE TITLE
Support bigint PK fields for QGIS >= 2.16

### ISSUE THREAD

**Issue by mandsch** [bstroebl/DataDrivenInputMask#3]
We experience issues with current 2.18 QGIS versions, when accessing n2m relations via DataDrivenInputMask. I assume it is not taking the foreign keys in the relation table into account, instead it uses the PK of the relation table. It is working with QGIS 2.14. Where there changes in the QGIS-Python-SQL API?

Cheers, Michael from Freiburg

**Comment by bstroebl** [comment]
Hallo Michael,
DataDrivenInputMask uses plain SQL to access the database, so QGIS is not involved here. Could you provide the DDL of the table(s) in question and a screenshot of the resulting mask?
Which PostgreSQL version are you running?
Bernhard

**Comment by mandsch** [comment]
Hi Bernhard, 
yep, that was my fear, that it's actually not related to QGIS. I'll send you the DDL of the relevant tables. Postgres-Version 9.1.19 (on SLES).
Thx, Michael

**Comment by mandsch** [comment]
Hi Bernhard, 
one thing more: I think with QGIS 2.18 I started to use the central authentication mechanism... Could that be a problem? Thx, Michael

**Comment by bstroebl** [comment]
Hi Michael,
problem is the bigint field. Until QGIS 2.14 bigint PK fields were handled the same as integer PK fields, i.e. QGIS' feature.id() was identical with the feature's PK value. Since QGIS 2.16 if the PK is a bigint there is a mapping in place assigning id values to pk values. Thus QGIS can support all types of PK fields.
I konow about this problem but did not fix it yet.

**Comment by bstroebl** [comment]
Fixed in new version 1.3.0
